name: Python Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # 指定所需的 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
      working-directory: ${{ github.workspace }}
    
    - name: Run Python script
      run: python main.py # 替换为你的 Python 脚本文件名
