name: Run Python Script

on:
  push:
    branches:
      - main  # 触发分支，可以根据需要更改

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # 指定Python版本

      - name: Install dependencies
        run: |
          pip install requests  # 安装requests模块
          pip install -r requirements.txt  # 安装其他依赖（如果有的话）

      - name: Run Python script
        run: python main.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add A.txt
          git commit -m "Update A.txt"
          git push
